# Generated by Django 5.1 on 2024-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirm',
            name='code',
            field=models.IntegerField(),
        ),
    ]
