# Generated by Django 5.1 on 2024-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userconfirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirm',
            name='code',
            field=models.BigIntegerField(),
        ),
    ]
