# Generated by Django 5.1 on 2024-08-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='UserConfirm',
        ),
    ]
